server:
  port: 8088

spring:
  application:
    name: empoyee-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
